# .github/workflows/ci.yml

name: Java CI

on: [push, pull_request]

jobs:
	build:
		runs-on: ubuntu-latest
			
			steps:
				
			# Step 1: Checkout code	 
			- uses: actions/checkout@v4
			
			# Step 2: Set up Java JDK 21 (Temurin)
			-name: Set up JDK 21
			uses: actions/setup-java@v4
			with:
				java-version: '21'
				distribution: 'temurin'
				
			# Step 3: Build project with Maven	
			- name: Build with Maven
				run: mvn clean install 
				
			# Step 4: Run tests with Maven
			- name: Run Tests
				run: mvn test